### ISSUE TITLE
how to display the data got from api?

### ISSUE THREAD

**Issue by ruffianhy** [google/cadvisor#1037]
i have got data like this:
{
    "timestamp": "2016-01-05T13:36:09.408512077Z",
    "cpu": {
        "usage": {
            "total": 1404205576127,
            "per_cpu_usage": [
                647568490692,
                756637085435
            ],
            "user": 667400000000,
            "system": 222080000000
        },
        "load_average": 0
    },
    "diskio": {
        "io_service_bytes": [
... ...
And i want to display them in my own website just like cadvisor .i donnot know the way to compute them(transform cpu usage to percentage, diskio and network...)

**Comment by timstclair** [comment]
Please re-post your question to stackoverflow.

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes (and cAdvisor) team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
