### ISSUE TITLE
Labels not compatible to latest prometheus version

### ISSUE THREAD

**Issue by MikeMichel** [google/cadvisor#1082]
see https://github.com/prometheus/prometheus/issues/1352 
i can not tell if it is really on cadvisors side to change labels for the prometheus endpoint or prometheus should allow dots again.

**Comment by vishh** [comment]
cc @jimmidyson

**Comment by jimmidyson** [comment]
We should probably sanitize labels then. That's a bit annoying tbh as you detailed in the Prometheus issue.

**Comment by jimmidyson** [comment]
@MikeMichel What version of cadvisor are you running? Looks like labels are properly sanitized to me but just want to confirm if this is a recent change.

**Comment by jimmidyson** [comment]
Labels were properly sanitized in 544b852a so only available in >= 0.20.4

**Comment by MikeMichel** [comment]
@jimmidyson i'm using a patched < 0.20.4 version because i need https://github.com/google/cadvisor/issues/1078 working before i can move to a newer official version

**Comment by jimmidyson** [comment]
I tagged 0.20.5 that includes that fix yesterday, but I have no access to push Docker images to Docker hub for this project I'm afraid.

@vishh Is this something you could take care of please?

**Comment by vishh** [comment]
Yup. On it.

**Comment by jimmidyson** [comment]
Closing this now as the labels are properly sanitized, just waiting on a docker image being tagged (come on @vishh :stuck_out_tongue:).

**Comment by beorn7** [comment]
Just as an afterthought: The invalid label names could only be exposed because the code "cheats" with the metric descriptors. If [`EnableCollectChecks`](https://godoc.org/github.com/prometheus/client_golang/prometheus#EnableCollectChecks) would have been set, the scrape would have resulted in an error even without the stricter checks the newer Prometheus server performs.

The upcoming revamp of `client_golang` will always perform those checks. It will also make it more obvious where the "cheating" is happening and the programmer is in their own to not create invalid metrics. (The primary goal is to detect all invalid metrics at start-up time, not only at scrape time. But that's not possible if label names are set dynamically.)
