### ISSUE TITLE
Document changes for the v0.24 release

### ISSUE THREAD

**Issue by timstclair** [google/cadvisor#1431]
**DRAFT**

- inode stats (total & available)
- Improved robustness to partial failures
- Metrics collector improvements
  - Added ability to directly use endpoints from the container itself
  - Allow SSL endpoint access
  - Ability to provide a certificate which is exposed to custom endpoints
- Lots of bug fixes, including:
  - Devicemapper thin_ls fixes
  - Prometheus metrics fixes
  - Fixes for missing stats (memory reservation, FS usage, etc.)

---

If you worked on a new feature or large change to cAdvisor in the last couple months, please leave a comment here.

PR's since the last non-cherrypick release: https://github.com/google/cadvisor/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Amerged%20merged%3A%3E2016-05-19%20

@vishh @ncdc @derekwaynecarr @jimmidyson @sjenning @mwringe @Random-Liu @ronnielai @pmorie

**Comment by ncdc** [comment]
Mine were fixes to devicemapper fs stats and/or thin_ls, so all devicemapper related.

**Comment by mwringe** [comment]
The main support I added was for custom metrics. This includes being able to directly use endpoints from the container itself (instead of having full hardcoded URLs), allowing SSL endpoint access, and being able to provide a certificate which is exposed to custom endpoints (so the endpoints can verify that it is cAdvisor asking for the metrics).

If there is anything in particular you would like for me to elaborate on, please let me know.

**Comment by derekwaynecarr** [comment]
I added support to optionally include inode information for devices that supported them.
