### ISSUE TITLE
Cannot create elasticsearch client when using remote container in Docker Swarm

### ISSUE THREAD

**Issue by johnharris85** [google/cadvisor#1516]
Possibly related to #881? 

Created a swarm of 3 Docker hosts. Elasticsearch running on one node using this command:

```
docker service create --network monitoring \
  --mount "type=volume,target=/usr/share/elasticsearch/data" \
  --constraint node.hostname==swarm-2 \
  --name elasticsearch elasticsearch:2.4.1
```

Cadvisor running globally on all 3 nodes. Starting cadvisor container with the following command:

```
docker service create --name=cadvisor \
-p 8081:8080 \
--mount "type=bind,src=/,dst=/rootfs,readonly=true" \
--mount "type=bind,src=/var/run,dst=/var/run,readonly=true" \
--mount "type=bind,src=/sys,dst=/sys,readonly=true" \
--mount "type=bind,src=/var/lib/docker,dst=/var/lib/docker,readonly=true" \
--mode global \
--container-label com.leftshift.group=DEV \
--network monitoring \
google/cadvisor:v0.24.1 \
-storage_driver=elasticsearch \
-storage_driver_es_host="http://elasticsearch:9200"
```

All the containers fail with:

 `F1026 22:18:44.464668       1 cadvisor.go:117] Failed to initialize storage driver: failed to create the elasticsearch client - no Elasticsearch node available`.

Giving the `-storage_driver_es_host=<elasticsearch_service_vip>:9200` it works fine. However if I create cadvisor without the es-specific options, then `docker exec -it <cadvisor_container> wget elasticsearch:9200` it can connect to ES without issue. 

ES is published on the correct IP (the VIP, 10.0.0.2 in this case), bound to all interfaces in that container. Not sure really what the issue is here.

Interesting complication, my colleague runs exactly the same setup (same version of everything) and it works just fine using `elasticsearch` instead of the service VIP. Worked through our setups and can't see any differences at all (running the swarm using `docker-machine`).

**Comment by mavenugo** [comment]
@johnharris85 network-scoped DNS records are gossiped/synchronized only on the Swarm nodes where there is atleast 1 task is attached to the corresponding network. In this case, the network `monitoring` is made active in 1 node where the `elasticsearch` task is launched. Since no other node is scheduled with any other tasks in that network `monitoring`, it is not gossiped yet. 
After the cadvisor service launches the tasks in other nodes, the network scoped DNS records are gossiped to these nodes. It is possible that the cadvisor containers are aggressively failing if the DNS record is not synchronized by the time the cadvisor container starts. It sounds like a timing issue.

Just to confirm this theory, can you launch a dummy service and keep it running in network `monitoring` with `--mode global` before launching the cadvisor service. That will make sure the DNS records are synchronized in these nodes when cadvisor container comes up.

**Comment by johnharris85** [comment]
Thanks @mavenugo, other containers (on other hosts) are able to connect to elasticsearch via the service name. I also did as you suggested just to confirm and brought up a dummy global service on that network and then started cadvisor, same result. It seems like an issue with the elastic client library maybe (or potentially the elasticsearch listening host settings?) except when using the IP it works fine, and my colleague under an identical setup has no issues at all, yet mine are consistently reproducible :p

**Comment by johnharris85** [comment]
So this is fixed by adding `--advertise-addr <node_IP>` to `docker swarm join ...` on my secondary managers. There's no warning, and the (Swarm) docs say it should be very rarely required. Can't explain technically what's going on here though, that curl etc works but cadvisor doesn't.
