### ISSUE TITLE
Only track some containers

### ISSUE THREAD

**Issue by vmarmol** [google/cadvisor#152]
As @crosbymichael mentioned in IRC and also a way for us to narrow down what we track when we start doing heavier things.

**Comment by dipankar** [comment]
@rjnagal Was thinking about implementing filtering by container aliases, any pointers as to what you guys decided approach wise?

**Comment by rjnagal** [comment]
I think the main feature here was to support regexes, so that we can filter out, say only docker containers. That way, we don't need to update the list when a new container shows up. 

We can probably accept the input through container_hints. We can accept aliases too to target specific containers, but doing just aliases makes regex matching harder.

The problem I ran into while trying this out was the way cAdvisor is structured now.  To track a container, we need to track all its parents. This means that we need to separate out discovering new containers from tracking. It requires bit of restructuring that we decided not to pursue back in Oct.

Feel free to take a shot at it. I'll take another look too. Unassigning from me for now.

**Comment by vmarmol** [comment]
Bug scrub: Do we still need this? Initially it was to deal with high resource usage, but we were able to mitigate that with some work.

**Comment by denderello** [comment]
We had a discussion about this topic today and would help us a lot to lower the amount of data that is transferred to InfluxDB because we are not interested in all data collected by cAdvisor. What's your opinion on this?

**Comment by rjnagal** [comment]
@denderello This is doable. We can add a flag(comma-separated values) or a config file to whitelist columns to push.

**Comment by thaJeztah** [comment]
Does cAdvisor use the docker daemon to get the list of containers? If it does, the "labels" proposal (https://github.com/docker/docker/pull/9882) could offer additional ways to filter containers; e.g. all containers having a label `com.google.cadvisor.group=some-group`

**Comment by vmarmol** [comment]
It does not, but it can get labels from Docker when those are available. We
do talk to the Docker API to get extra info about the containers.

**Comment by denderello** [comment]
@rjnagal sounds like a good approach. Judging from our use cases multiple expressions could definitely make it easier instead of trying to come up with one big expressions that tries to fit all matches.

**Comment by vmarmol** [comment]
@rjnagal we merged `--dockeronly` should we close this?

**Comment by rjnagal** [comment]
--docker_only solves part of the problem. I am not going to look at the regex part anytime soon.

So we can close for now.
