### ISSUE TITLE
container_memory_usage_bytes prometheus metrics help doesn't specify what memory we are measuring

### ISSUE THREAD

**Issue by octete** [google/cadvisor#1744]
As per https://github.com/google/cadvisor/issues/975, two more stats were added: RSS + cache, as `container_memory_usage_bytes`, which seems to come from cgroup stats includes resident memory, caches and swap.

Could we please modify the definition of it in `metrics/prometheus.go` so that it specify what the differences of these metrics are? (specifically as compared to `container_memory_rss` and `container_memory_cache`)
```go
            }, {
                name:      "container_memory_usage_bytes",
                help:      "Current memory usage in bytes.",
                valueType: prometheus.GaugeValue,
                getValues: func(s *info.ContainerStats) metricValues {
                    return metricValues{{value: float64(s.Memory.Usage)}}
                },
```

as it is not very clear from the helper message?

If you prefer, I can send a PR, but I thought that maybe as this is just a simple help message change, it could be quicker this way.

If you think this is fine and you want the PR, please, let me know and I will send you one :-)

Thanks

**Comment by dashpole** [comment]
Thanks for pointing this out.

**Comment by dashpole** [comment]
Can you make sure #1759 is what you were looking for?

**Comment by ylfforme** [comment]
> 
> 
> Thanks for pointing this out.

can I understand like this？ ”container_memory_usage_bytes” is rss + cache + swap
“container_memory_rss” is just rss not include cache and swap

**Comment by xigang** [comment]
mark

**Comment by thomasf1234** [comment]
@jstangroome 
Might be my lack of understanding but do you how `container_memory_mapped_file` integrates with this? 

The docs appear to say that the `rss` field under 'memory.stat` is not the true RSS for the cgroup (https://github.com/torvalds/linux/blob/v4.15/Documentation/cgroup-v1/memory.txt#L524-L530). 

Does this imply the following relationship? 

`container_memory_usage_bytes` == `container_memory_rss` + `container_memory_mapped_file` + `container_memory_cache` + `container_memory_swap` + `container_memory_kernel`.

**Comment by dongwangdw** [comment]
> @ylfforme
> 
> `container_memory_usage_bytes` == `container_memory_rss` + `container_memory_cache` + `container_memory_swap` + kernel memory.
> 
> But kernel memory is not exposed as a metric yet, see #2138

Why this metrics includes so much, it has a different result as `kubectl top`.

**Comment by rdzimmer** [comment]
@thomasf1234 
_Although upon analysis of the corresponding metric values, the following relationship appears correct just not sure the role of mapped_file (perhaps a subset of cache?):
container_memory_usage_bytes == container_memory_rss + container_memory_cache + container_memory_kernel_

My understanding is you are correct that it is a subset of the cache.  When files are mapped (mmap) they are loaded into the page cache, so it would be double counting to include it.  Good to have it though since it can be useful to count and know how much mapped file area is used vs the (page) cache as a whole.  

_"Accesses to not-yet-loaded parts of the mmapped region are handled in the same way as swapped out pages."_
https://www.gnu.org/software/libc/manual/html_node/Memory_002dmapped-I_002fO.html
_"The page fault handler locates the vm_area_struct struct in the process’s address space and eventually finds the pages in the page cache that map to the file offsets being accessed. These pages are marked as dirty if there’s a write and mapped directly to user space — this way there is no need to copy data from kernel to user space.
Once you’re done using the memory mapped area, the munmap system call can be used to free up the memory. Any data written to the page cache is periodically committed to disk, although you can force it with msync. While mmap is useful, it definitely has drawbacks. Misses in the page cache always result in the page being read into the cache even if a write is going to overwrite the contents."_
https://medium.com/i0exception/memory-mapped-files-5e083e653b1

I also believe swap is simply in there for (future) completeness, since it is disabled today.  Always a bunch of zeros for me, but maybe there's a current usage I'm not aware of.  https://github.com/kubernetes/kubernetes/issues/53533
