### ISSUE TITLE
cadvisor command line opts vs env vars

### ISSUE THREAD

**Issue by jchauncey** [google/cadvisor#179]
I wonder if making the cadvisor container take environment vars instead of command line opts for things like -storage driver would make it easier to use with the upcoming docker deployment tools?

**Comment by marcellodesales** [comment]
@vishh I'm having the same issue... I tried to set the variables using `docker-compose` through variable replacement https://docs.docker.com/engine/reference/builder/#environment-replacement. 

I tried to add `CADVISOR_HOST` as a variable in the environment and that did not work.

```
cadvisor_1        | E0217 06:27:54.241068       1 memory.go:91] failed to write stats to influxDb - parse http://$%7BCADVISOR_HOST%7D/write: percent-encoded characters in host
```

Maybe instead of the command instruction, we could pass env vars and all would be good.

**Comment by matcornic** [comment]
@vishh one solution would be using [Viper](https://github.com/spf13/viper) instead of `flags`. It would be more flexible than just simple flags. But it's a breaking change, because with [pflag](https://github.com/spf13/pflag), single dashes does not have same meaning than classic flags. Equivalent would be [using double dashed `--option`](https://github.com/spf13/pflag#command-line-flag-syntax)

**Comment by iwankgb** [comment]
Closing very old issue.
