### ISSUE TITLE
how to compare the result of linux top cmd with cadvisor ?

### ISSUE THREAD

**Issue by liwei00wade** [google/cadvisor#2086]
give me some point, thanks.

**Comment by dashpole** [comment]
cAdvisor uses the cgroup hierarchy as its source for metrics, rather than /proc files, so they won't be the same.  CAdvisor's memory usage metrics, `container_memory_usage_bytes / container_spec_memory_limit_bytes`, maps roughly to memory usage %age on linux, and `rate(container_cpu_usage_seconds_total)` is about maps to cpu usage.
