### ISSUE TITLE
containers using MADV_FREE do not see their memory usage decrease

### ISSUE THREAD

**Issue by sylr** [google/cadvisor#2242]
I've a bunch of containers running Thanos (a golang app which proxy prometheus queries).

The latest version of Thanos has been compiled with go 1.12 which use `MADV_FREE` to release memory back to the system instead of `MADV_DONTNEED` in go 1.11.

Unfortunately it seems that cadvisor does not see the memory being released with `MADV_FREE`.

Here a graph showing `container_memory_usage_bytes` after switching back to `MADV_DONTNEED` instead of `MADV_FREE`  using  `GODEBUG=madvdontneed=1`.

![Screenshot_65](https://user-images.githubusercontent.com/153052/57789027-68b3d280-7738-11e9-8c40-e9afe1c62a91.png)
 
I don't know if cadvisor can do something about it though.

**Comment by bwplotka** [comment]
Related change for Golang: https://github.com/golang/go/issues/23687 but did not have a chance to dive into what this option does / what's expected. The effect is quite scary though.

**Comment by bwplotka** [comment]
https://github.com/prometheus/prometheus/issues/5524 seems like Go 1.12.5 has this fixed

**Comment by dashpole** [comment]
I don't think cAdvisor can do anything here.  cAdvisor just reports the value from cgroup files.  This is either a golang issue, as suggested by @bwplotka above, or a kernel issue.

**Comment by bwplotka** [comment]
There is a fix. Use `container_memory_working_set_bytes` metric instead (:

**Comment by bwplotka** [comment]
After couple of tests it's clear that `container_memory_working_set_bytes` is not giving what we want, so "memory saturation of the container". There are many people that uses this as a reference in alerts etc

Actual allocated memory on the heap of 2 Golang processes in each container:
![(095)](https://user-images.githubusercontent.com/6950331/58762188-624d9500-8545-11e9-81fe-5ab670fba90c.png)

`container_memory_working_set_bytes` is showing magic numbers:
![image](https://user-images.githubusercontent.com/6950331/58762201-9aed6e80-8545-11e9-97a3-5eb3887c76f6.png)

For fun (because this is misleading, but works as expected) `container_memory_usage_bytes`:
![image](https://user-images.githubusercontent.com/6950331/58762208-a93b8a80-8545-11e9-8b78-bdb12e4774fa.png)

Anyway, the outcome is: cadvisor is not having any way to tell us about memory saturation anymore with newest Golang MADV logic ): 

cc @sylr @gouthamve

**Comment by sylr** [comment]
@bwplotka I wouldn't trust go_memstats_... as I find it particularly hard to understand  what they really represent (see: https://github.com/golang/go/issues/32284).

**Comment by bwplotka** [comment]
Wrote a post about this in details here: https://bwplotka.dev/2019/golang-memory-monitoring/
