### ISSUE TITLE
when computer container cpu usage through the metrics/cadvisor, the value larger than limited value and `top` command's value

### ISSUE THREAD

**Issue by zhangxingdeppon** [google/cadvisor#2362]
**What happened**:
hi, buddies, I met a problem, when computer container cpu usage through the metrics/cadvisor, the value larger than `top` command's value, I need a exactly value like `top` command,  can you give me some ideas? thanks

here is a example to show you, for example  deployment  `hux7rjho76zj3l2s-notebook`.
this is example deployment yaml:
<pre><code>
[root@ecs-5274-0318501 ~]# kubectl get deploy hux7rjho76zj3l2s-notebook -n aipaas-notebook -o yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-12-23T05:51:18Z"
  generation: 1
  labels:
    app: hux7rjho76zj3l2s-notebook
  name: hux7rjho76zj3l2s-notebook
  namespace: aipaas-notebook
  resourceVersion: "44842674"
  selfLink: /apis/extensions/v1beta1/namespaces/aipaas-notebook/deployments/hux7rjho76zj3l2s-notebook
  uid: 3d2c0dc0-2548-11ea-a14a-fa163ebce782
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: hux7rjho76zj3l2s-notebook
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hux7rjho76zj3l2s-notebook
    spec:
      containers:
      - env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: none
        image: 172.16.1.222:10004/notebook/deeplearning_jupyter_limit_token:v1.3
        imagePullPolicy: Always
        name: hux7rjho76zj3l2s-notebook
        ports:
        - containerPort: 8888
          name: jupyter
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: "8589934592"
          requests:
            cpu: 500m
            memory: "2147483648"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /src/notebooks/
          name: hux7rjho76zj3l2s-notebook
      dnsPolicy: ClusterFirst
      nodeSelector:
        node: worker
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 999
        runAsUser: 999
      terminationGracePeriodSeconds: 30
      volumes:
      - name: hux7rjho76zj3l2s-notebook
        persistentVolumeClaim:
          claimName: hux7rjho76zj3l2s-pvc
</code></pre>
cpu `limited:2, request:0.5`

 Firstly, use the metric/cadvisor computer the value, the promQL is `rate(container_cpu_usage_seconds_total{container_name=~"hux7rjho76zj3l2s-notebook.*"}[1m])`
 I have tried to decrease or increase the time, like `5m`/`30s`, but the value is also not exact.
 
through a period of time, you will find below cpu monitor grafana:

![image](https://user-images.githubusercontent.com/16789841/71348315-3fe59c80-25a7-11ea-920f-e9540707d2ef.png)

you will find sometime the cpu value larger than 2 a lot, the peak is `2.3`, but the value is exact returned by `top` command:

![image](https://user-images.githubusercontent.com/16789841/71348461-8e933680-25a7-11ea-8b99-cc99ccf6b56e.png)

**What you expected to happen**:
I need a exact value about container cpu usage, thanks.

**Comment by dashpole** [comment]
Does it still exceed the limit when using the longer (e.g. 5m) rate window?  Those spikes are often caused by a using a rate window that is too low.  

The cumulative CPU metrics you are taking a rate over are all "exact", but the rate you are taking is an average over the specified time period.  What you probably mean by "exact" is the average taken over the same time period as top, e.g. a 1s average rather than your current 1m average.  If that is what you are trying to acheive, you can decrease cAdvisor's housekeeping interval (default 10-15s), decrease the scrape interval (default 30s IIRC), and decrease your rate window (1m).  But be aware that cAdvisor's CPU and memory usage will increase (sometimes greatly) if you lower the housekeeping interval too low.

**Comment by zhangxingdeppon** [comment]
@dashpole yes, when using the longer (e.g. 5m) rate window, it will lower the limit a lot, but it's also not exact like `top`,  according to you answer, I changed the cAdvisor's housekeeping interval value to 1s,  It resolved the problem,  thank you very much;
In addition, I feel a little confused, why not metric/cadvisor explicitly calculate the percentage value, and add it in metrics like `container_cpu_usage_percentage 50% `, but not `container_cpu_usage_seconds_total`?

**Comment by dashpole** [comment]
To give a percentage, we would need to first produce a rate, and that assumes a specific time window.  As you found out, different users prefer different time windows, since there is a trade-off between performance and precision.  We generally prefer providing the metrics required (cumulative CPU usage, the container, pod, and node CPU shares + quota) so users can construct what they need, such as container_cpu_usage_percentage_container_limits over 10s, or container_cpu_usage_percentage_node_limits over 60s, etc.

**Comment by zhangxingdeppon** [comment]
@dashpole excellent,  I got it, thank you very much.
