### ISSUE TITLE
CAadvisor https support for /metric endpoint

### ISSUE THREAD

**Issue by SharedMocha** [google/cadvisor#2539]
It would be good if CAadvisor can support https on /metrics endpoints.
Today we use a reverse proxy but looking for alternatives like making /metrics https. 
One thought is to pass root cert, tls cert, and key files via env variable to CAadvisor container.

**Comment by dashpole** [comment]
We used to have some security features built into cAdvisor, but found that we were not able to keep those up to date.  We removed them and have since encouraged the use of reverse proxies.  Unless there is a reason something cannot be done in a reverse proxy, I think we should stick with the current guidance.

**Comment by SharedMocha** [comment]
Thanks, @dashpole for your reply. I will use a reverse proxy.
