### ISSUE TITLE
manager.go:694] Error getting data for container / because of race condition

### ISSUE THREAD

**Issue by sgpinkus** [google/cadvisor#3407]
Running cadvisor like:

```
# VERSION=v0.47.2 # use the latest release version from https://github.com/google/cadvisor/releases
sudo docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:ro \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --volume=/dev/disk/:/dev/disk:ro \
  --publish=8080:8080 \
  --privileged \
  --device=/dev/kmsg \
  gcr.io/cadvisor/cadvisor:$VERSION \
  --docker_only=true \
  --disable_root_cgroup_stats=true
```

Gives error log every 15s:

> manager.go:694] Error getting data for container / because of race condition

Setting `--disable_root_cgroup_stats=false` make this error log go away.

**Comment by sgpinkus** [comment]
> The 15s interval you are seeing is likely your Prometheus server scraping at every 15s (the default)?

Yes that would be it!

**Comment by hhromic** [comment]
> The error message itself is a bit misleading, as this is not really a race condition.
> The `/` container should not be added to the entities to collect data for when root cgroup stats are disabled.
> But I have not digged deeper on where that is being done to propose a proper fix.

I got some time now and did dig deeper.
Turns out that container metrics are collected recursively starting from `/` here: <https://github.com/google/cadvisor/blob/688835d77b199a4e95497b7d7d7b3580d5b03860/metrics/prometheus.go#L1822>

Therefore it is normal to hit `/` during collection even when root cgroup stats are disabled.
That being said, I think indeed refactoring the error logging to `V(4)` as done in #3341 is an appropriate solution.
I will open a PR for it now :)
