### ISSUE TITLE
Incorrect path docker/libcontainer/network

### ISSUE THREAD

**Issue by dwitzig** [google/cadvisor#533]
Since this (https://github.com/docker/libcontainer/pull/367) merge in docker/libcontainer
the following paths are incorrect 
https://github.com/google/cadvisor/search?utf8=✓&q=%22github.com%2Fdocker%2Flibcontainer%2Fnetwork%22&type=Code

**Comment by vmarmol** [comment]
Libcontainer recently updated their API which made a lot of breaking changes. We have not yet updated to the new API. However, since we use godep we are not affected by this change. Our builds should be clean, if not let us know :)

More detail on building: https://github.com/google/cadvisor/blob/master/docs/build.md
