### ISSUE TITLE
Support resolution in stats API

### ISSUE THREAD

**Issue by vishh** [google/cadvisor#605]
Now that we have time range for stats queries, it will be helpful for users to specify a `resolution` which is currently 1 second by default.

**Comment by vmarmol** [comment]
We already have a global flag for collection interval. Do you mean: ask for data at 2s intervals? We can do this only if your interval > our collection interval. With dynamic housekeeping it gets interesting, but we can return an error in those cases.

**Comment by vmarmol** [comment]
The user would not get data that was nice in their resolution interval unless it is a multiple of our collection interval though.

**Comment by vishh** [comment]
Yes. The API should allow querying stats at a lower resolution. What is the
issue with dynamic housekeeping?

**Comment by vmarmol** [comment]
Do you mean an API to dynamically adjust the collection frequency?

**Comment by vishh** [comment]
Nope. I mean just for the query.

**Comment by vmarmol** [comment]
Ah I see what you mean. We should be able to as long as the requested resolution is > the collection interval (we can't do 0.5s if we gather every second). If the resolution is not a multiple of the collection interval then you may not get stats as you expect. For example, if we collect every 2s and user asks for resolution of 5s we'd need to interpolate the first or only do every 2 of the user's queries.

Dynamic housekeeping makes it interesting since we may have non-uniform intervals on the same stat: 1s, 2s, 4s

**Comment by iwankgb** [comment]
Closing very old issue.
