### ISSUE TITLE
Is there some need to make cadvisor metrics reporting configurable?

### ISSUE THREAD

**Issue by allencloud** [google/cadvisor#654]
Hi 

I think making reporting metrics configurable can be reasonable.

If a user wants to collect some specific metric, let him configure. If he does not need some metrics, just abandon them not reporting to the storage, such as influxdb. As a result, it can save more space in influxdb when doing this.

**Comment by vmarmol** [comment]
@allencloud, do you mean to configure which of the existing metrics to export or to allow cAdvisor to collect custom user metrics we don't today?

**Comment by allencloud** [comment]
configure which of the existing metrics to export @vmarmol

**Comment by vishh** [comment]
We can add a regex whitelist to control the metrics being pushed by
individual storage backends. Is this something you are interested in
working on? We are happy to take a PR for this!

**Comment by allencloud** [comment]
Yes, it is what I am interested in. And I can prepare PR for it. @vishh

**Comment by vmarmol** [comment]
A regex is probably not a good way to handle this since metrics today are exported as structures JSON objects and any regex against a string ID will be specific to the storage driver it is created.

Alternatives I can think of are:
- Define each of the metrics today globally with some string ID instead of the objects we define today
- Parallel JSON structure that defines whether that metric is exported (default to true) e.g.:

I think the second is better, easier to configure, and better aligns with what we do today.

**Comment by iwankgb** [comment]
Closing very old issue.
