### ISSUE TITLE
manager Exists() function does not set namespace

### ISSUE THREAD

**Issue by bdanofsky** [google/cadvisor#718]
the manager.go file implements an Exists() function for the manager.
For Docker name spaced containers (or any other namespace) the name space is not set when the search is done.
This same issue seems to apply to:
getContainer()
getContainerData()
createContainer()
destroyContainer()
getContainersDiff()
et al.

**Comment by rjnagal** [comment]
The comments don't make it clear, but all the mentioned interfaces are meant for raw namespace (full path). Since that is the default namespace, whenever a method takes in a container name as a string, it is assumed to be in default namespace and we trivially convert it to a namespaced name by not filling in the namespace.

I'll add comments around the code to reflect that.

**Comment by vmarmol** [comment]
@bdanofsky I'm curious, are you consuming the cAdvisor manager as an API instead of using the remote one? In the remote one we are starting to have the concept of "Docker" container, the internal interfaces are all raw containers pretty much. We could do a better job in that interface as @rjnagal mentioned. No one has used that API till now so it wasn't prioritized, which is why I ask :)

**Comment by bdanofsky** [comment]
Victor:
I was using the manager code to access container stats directly.  What caught me off guard was I called exists() on a docker container and got back false.  After investigating I say the name space was not set.  I should have noted all the docker Api calls have docker in the name, I should have caught that faster.
Regards

Brad

**Comment by rjnagal** [comment]
closing this one for now.
