### ISSUE TITLE
cAdvisor can't find docker when running inside a container

### ISSUE THREAD

**Issue by smarterclayton** [google/cadvisor#770]
Testing containerized Kubelet and seeing:

```
W0611 21:27:27.828300       1 container_manager_linux.go:68] [ContainerManager] Failed to ensure Docker is in a container: failed to find pid of Docker container: exit status 1
```

This is normal because Docker isn't in the pid namespace of the kubelet - but either cAdvisor needs to use the same pid namespace escape tricks that the kubelet uses for mounts, or we need to run the kubelet outside of a pid namespace, which makes other things regarding the container much harder.

**Comment by smarterclayton** [comment]
Nm, I wasn't mounting in the right things.

**Comment by smarterclayton** [comment]
Nm, still happening :)

**Comment by rjnagal** [comment]
This bit of code is in kubelet. It creates a new cgroup and tries to move docker processes there.

I think the problem is that kubelet is execing `pidof docker` to find docker processes. In cadvisor, we mount system root at /rootfs and use that to proxy process listing.

kubelet can do the same with `chroot /rootfs pidof docker`

Three lines of change, but needs to go in kubelet :)

Are the namespaced kubelet changes getting in? I can make the kubelet change if someone is willing to merge it in.

**Comment by smarterclayton** [comment]
Ah, sorry.  Jumped the gun.  It's not in Kube but we're enabling it in OpenShift and testing it.  Not a high priority fix.

**Comment by smarterclayton** [comment]
Will move this to Kube

**Comment by smarterclayton** [comment]
Moved to Kube
