### ISSUE TITLE
Set up auto builds for tags on Docker hub

### ISSUE THREAD

**Issue by jimmidyson** [google/cadvisor#982]
Not sure who owns this but now that Docker hub supports automatically building Docker images tagged the same as git tags as they're added this would make it less manual on every release.

I have no access as this is under the google org on Docker hub...

@vishh I guess this is you?

**Comment by vishh** [comment]
IIUC, docker hub builds require a self-sufficient Dockerfile. We can automate `canary` builds with dockerhub, but I don't see how we can setup release builds since releases require a `go build` prior to `docker build`. 

The jenkins project has an build project that is supposed to push `canary` images on every commit to `master`. We can extend that to push a new release image whenever a new tag is added.

**Comment by jimmidyson** [comment]
Ah yes I assumed it was a Docker hub build but you are correct. Thanks!
